### ISSUE TITLE
Feedback on week 13 project progress for CS2113-T13-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T13-1/main#386]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @sinteary for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-1/main/pull/234 https://github.com/AY1920S1-CS2113-T13-1/main/issues/348 https://github.com/AY1920S1-CS2113-T13-1/main/issues/346 https://github.com/AY1920S1-CS2113-T13-1/main/issues/343 https://github.com/AY1920S1-CS2113-T13-1/main/issues/249 https://github.com/AY1920S1-CS2113-T13-1/main/issues/235 https://github.com/AY1920S1-CS2113-T13-1/main/issues/209 https://github.com/AY1920S1-CS2113-T13-1/main/issues/205 https://github.com/AY1920S1-CS2113-T13-1/main/issues/22 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @lucria for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-1/main/pull/374 https://github.com/AY1920S1-CS2113-T13-1/main/pull/371 https://github.com/AY1920S1-CS2113-T13-1/main/pull/366 https://github.com/AY1920S1-CS2113-T13-1/main/pull/361 https://github.com/AY1920S1-CS2113-T13-1/main/pull/357 https://github.com/AY1920S1-CS2113-T13-1/main/pull/352 https://github.com/AY1920S1-CS2113-T13-1/main/pull/336 https://github.com/AY1920S1-CS2113-T13-1/main/pull/324 https://github.com/AY1920S1-CS2113-T13-1/main/pull/323 https://github.com/AY1920S1-CS2113-T13-1/main/pull/321 https://github.com/AY1920S1-CS2113-T13-1/main/pull/320 https://github.com/AY1920S1-CS2113-T13-1/main/pull/318 https://github.com/AY1920S1-CS2113-T13-1/main/pull/239 https://github.com/AY1920S1-CS2113-T13-1/main/pull/227 https://github.com/AY1920S1-CS2113-T13-1/main/issues/343 https://github.com/AY1920S1-CS2113-T13-1/main/issues/314 https://github.com/AY1920S1-CS2113-T13-1/main/issues/311 https://github.com/AY1920S1-CS2113-T13-1/main/issues/293 https://github.com/AY1920S1-CS2113-T13-1/main/issues/288 https://github.com/AY1920S1-CS2113-T13-1/main/issues/287 https://github.com/AY1920S1-CS2113-T13-1/main/issues/275 https://github.com/AY1920S1-CS2113-T13-1/main/issues/271 https://github.com/AY1920S1-CS2113-T13-1/main/issues/268 https://github.com/AY1920S1-CS2113-T13-1/main/issues/266 https://github.com/AY1920S1-CS2113-T13-1/main/issues/260 https://github.com/AY1920S1-CS2113-T13-1/main/issues/259 https://github.com/AY1920S1-CS2113-T13-1/main/issues/251 https://github.com/AY1920S1-CS2113-T13-1/main/issues/248 https://github.com/AY1920S1-CS2113-T13-1/main/issues/242 https://github.com/AY1920S1-CS2113-T13-1/main/issues/127 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @iamabhishek98 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-1/main/pull/384 https://github.com/AY1920S1-CS2113-T13-1/main/pull/383 https://github.com/AY1920S1-CS2113-T13-1/main/pull/380 https://github.com/AY1920S1-CS2113-T13-1/main/pull/375 https://github.com/AY1920S1-CS2113-T13-1/main/pull/369 https://github.com/AY1920S1-CS2113-T13-1/main/pull/362 https://github.com/AY1920S1-CS2113-T13-1/main/pull/358 https://github.com/AY1920S1-CS2113-T13-1/main/pull/347 https://github.com/AY1920S1-CS2113-T13-1/main/pull/325 https://github.com/AY1920S1-CS2113-T13-1/main/pull/384 https://github.com/AY1920S1-CS2113-T13-1/main/pull/383 https://github.com/AY1920S1-CS2113-T13-1/main/pull/380 https://github.com/AY1920S1-CS2113-T13-1/main/pull/375 https://github.com/AY1920S1-CS2113-T13-1/main/pull/369 https://github.com/AY1920S1-CS2113-T13-1/main/pull/362 https://github.com/AY1920S1-CS2113-T13-1/main/pull/358 https://github.com/AY1920S1-CS2113-T13-1/main/pull/347 https://github.com/AY1920S1-CS2113-T13-1/main/issues/343 https://github.com/AY1920S1-CS2113-T13-1/main/issues/342 https://github.com/AY1920S1-CS2113-T13-1/main/issues/338 https://github.com/AY1920S1-CS2113-T13-1/main/pull/325 https://github.com/AY1920S1-CS2113-T13-1/main/issues/298 https://github.com/AY1920S1-CS2113-T13-1/main/issues/296 https://github.com/AY1920S1-CS2113-T13-1/main/issues/286 https://github.com/AY1920S1-CS2113-T13-1/main/issues/285 https://github.com/AY1920S1-CS2113-T13-1/main/issues/284 https://github.com/AY1920S1-CS2113-T13-1/main/issues/270 https://github.com/AY1920S1-CS2113-T13-1/main/issues/247 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @seanlimhx for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-1/main/issues/343 https://github.com/AY1920S1-CS2113-T13-1/main/issues/241 https://github.com/AY1920S1-CS2113-T13-1/main/issues/212 https://github.com/AY1920S1-CS2113-T13-1/main/issues/85 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @dkenobi for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-1/main/pull/339 https://github.com/AY1920S1-CS2113-T13-1/main/pull/328 https://github.com/AY1920S1-CS2113-T13-1/main/pull/232 https://github.com/AY1920S1-CS2113-T13-1/main/issues/343 https://github.com/AY1920S1-CS2113-T13-1/main/pull/339 https://github.com/AY1920S1-CS2113-T13-1/main/issues/334 https://github.com/AY1920S1-CS2113-T13-1/main/issues/332 https://github.com/AY1920S1-CS2113-T13-1/main/issues/331 https://github.com/AY1920S1-CS2113-T13-1/main/pull/328 https://github.com/AY1920S1-CS2113-T13-1/main/issues/327 https://github.com/AY1920S1-CS2113-T13-1/main/pull/232 https://github.com/AY1920S1-CS2113-T13-1/main/issues/10 https://github.com/AY1920S1-CS2113-T13-1/main/issues/8 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @akshayeshenoi

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
